---
title: "04_describe"
author: Eric Torres, Lucia de Lamadrid, Konstantina Gkopi, Elena Iriondo and Jorge Santiago
format: html
editor: visual
---

## Data visualization and description

1.  Load packages

    ```{r}

    ```

2.  Read data

    ```{r}
    clean_df <- read.table('../data/02_metadata_long_filtered_label.tsv', header=TRUE, sep='\t')
    head(clean_df)
    ```

### Abundance of each OTU in samples

```{r}
clean_df |> 
  filter(Diet %in% c("LFPP", "Western")) |> 
  group_by(Source, Diet) |> 
  mutate(norm_rel_abundance = rel_abundance / sum(rel_abundance)) |> # Normalize within samples
  group_by(Source, Diet, Phylum) |> 
  summarise(mean_rel_abund = mean(norm_rel_abundance), .groups = "drop") |> # Calculate mean abundance
  group_by(Source, Diet) |> 
  mutate(mean_rel_abund = mean_rel_abund / sum(mean_rel_abund)) |> # Normalize mean abundances
  ggplot(aes(x = Diet,
             y = mean_rel_abund,
             fill = Phylum)) +
  geom_bar(stat = "identity",
           position = "stack") +
  facet_wrap(~ Source) + 
  labs(
    title = "Normalized Relative Abundance of OTUs",
    x = "Diet",
    y = "Relative Abundance (Proportion)",
    fill = "OTU"
  ) +
  theme_minimal() +
  theme(legend.position = "none")
## Decide among this one or the next one: this seems more explicative, but less aesthetic and the bars are smaller
```

```{r}
clean_df |> 
  filter(Diet %in% c("LFPP", "Western")) |> 
  group_by(Source, Diet) |> 
  mutate(norm_rel_abundance = rel_abundance / sum(rel_abundance)) |> # Normalize abundance within samples
  group_by(Source, Diet, Phylum) |> 
  summarise(mean_rel_abund = mean(norm_rel_abundance), .groups = "drop") |> # Calculate the mean relative abundances
  group_by(Source, Diet) |> 
  mutate(mean_rel_abund = mean_rel_abund / sum(mean_rel_abund)) |> # Normalize mean abundances so that the total for each one is 1
  ggplot(aes(x = Source,
             y = mean_rel_abund,
             fill = Phylum)) + 
  geom_bar(stat = "identity",
           position = "stack") +
  geom_hline(yintercept = 0) +
  facet_wrap(~ Diet) + 
  labs(
    title = "Normalized Relative Abundance of Phyla per source and diet type",
    x = "Source type",
    y = "Relative Abundance (Proportion)",
    fill = "Phyla"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom", # change when data augmentation has been done
        legend.text = element_text(size = 8),
        axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
clean_df |> 
  filter(Diet %in% c("LFPP", "Western")) |> 
  group_by(Source, Diet) |> 
  mutate(norm_rel_abundance = rel_abundance / sum(rel_abundance)) |> # Normalize abundance within samples
  group_by(Source, Diet, Class) |> 
  summarise(mean_rel_abund = mean(norm_rel_abundance), .groups = "drop") |> # Calculate the mean relative abundances
  group_by(Source, Diet) |> 
  mutate(mean_rel_abund = mean_rel_abund / sum(mean_rel_abund)) |> # Normalize mean abundances so that the total for each one is 1
  ggplot(aes(x = Source,
             y = mean_rel_abund,
             fill = Class)) + 
  geom_bar(stat = "identity",
           position = "stack") +
  geom_hline(yintercept = 0) +
  facet_wrap(~ Diet) + 
  labs(
    title = "Normalized Relative Abundance of Phyla per source and diet type",
    x = "Source type",
    y = "Relative Abundance (Proportion)",
    fill = "Class"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom", # change when data augmentation has been done
        legend.text = element_text(size = 8),
        axis.text.x = element_text(angle = 45, hjust = 1))
```

### Microbiota composition of mice with different diet and donor combination (relative abundance of phyla)

```{r}
#head(clean_df)
clean_df
```

```{r}
#With filtered data (only OTUs with >0.5%). If we don't see differences among the treatments as in the article that means we should use non-filtered data.

clean_df |> 
  filter(Donor )
```
